version: '3.6'
services:

######### FRONTENDS ##########

# Traefik Reverse Proxy
  traefik:
    hostname: traefik
    image: traefik:v1.7.16
    container_name: traefik
    restart: always
    networks:
      - default
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - GODADDY_API_KEY=${GODADDY_API_KEY}
      - GODADDY_API_SECRET=${GODADDY_API_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"
      - "traefik.docker.network=proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${USERDIR}/docker/traefik:/etc/traefik
      - ${USERDIR}/docker/shared:/shared
      
# Ghost - Ghost is a free and open source blogging platform
  ghost:
    image: ghost:4-alpine
    depends_on:
      - ghost-mysql
    container_name: ghost
    restart: always
    networks:
      - default
      - proxy
    volumes:
      - ${USERDIR}/docker/ghost/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      database__client: mysql
      database__connection__host: ghost-mysql
      database__connection__port: 3306
      database__connection__user: bethington
      database__connection__password: ${PASS}
      database__connection__database: ghost
      url: https://${DOMAINNAME}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ghost"
      - "traefik.port=2368"
      - "traefik.frontend.rule=Host:${DOMAINNAME}"  
      - "traefik.docker.network=proxy"
      
# Ghost - Ghost is a free and open source blogging platform
  adanation:
    image: ghost:4-alpine
    depends_on:
      - adanation-mysql
    container_name: adanation
    restart: always
    networks:
      - default
      - proxy
    volumes:
      - ${USERDIR}/docker/adanation/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      database__client: mysql
      database__connection__host: adanation-mysql
      database__connection__port: 3306
      database__connection__user: bethington
      database__connection__password: ${PASS}
      database__connection__database: adanation
      url: https://adanation.org
    labels:
      - "traefik.enable=true"
      - "traefik.backend=adanation"
      - "traefik.port=2368"
      - "traefik.frontend.rule=Host:adanation.org"  
      - "traefik.docker.network=proxy"
      
# Portainer - WebUI for Containers
  portainer:
    hostname: portainer
    image: portainer/portainer:latest
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      TZ: ${TZ}
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:portainer.${DOMAINNAME}"  
      - "traefik.docker.network=proxy"

# NextCloud – Your Own Cloud Storage
  cloud:
    image: nextcloud
    container_name: cloud
    hostname: cloud
    restart: always
    depends_on:
      - cloud-mysql
    networks:
      - default
      - proxy
    environment:
      MYSQL_PASSWORD: ${PASS}
      MYSQL_DATABASE: cloud
      MYSQL_USER: bethington
      MYSQL_HOST: cloud-mysql
      NEXTCLOUD_ADMIN_USER: bethington
      NEXTCLOUD_ADMIN_PASSWORD: ${PASS}
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.${DOMAINNAME}
      APACHE_DISABLE_REWRITE_IP: 1
    volumes:
      - ${USERDIR}/docker/cloud:/var/www/html
    labels:
      traefik.enable: "true"
      traefik.backend: cloud
      traefik.port: 80
      traefik.frontend.rule: Host:cloud.${DOMAINNAME}
      traefik.docker.network: proxy
      
# VS code server – VS Code running on a remote server, accessible through the browser.
  code:
    image: bethington/code-server
    container_name: code
    hostname: code
    restart: always
    networks:
      - proxy
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      PASSWORD: ${PASS}
      SUDO_PASSWORD: ${PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${USERDIR}:/home/coder"
    labels:
      traefik.enable: "true"
      traefik.backend: code
      traefik.port: 8080
      traefik.frontend.rule: Host:code.${DOMAINNAME}
      traefik.docker.network: proxy

# MineOS - MineOS is a web-based server front-end to centralize and simplify Minecraft sysadmin tasks.
  mineos:
    image: bethington/mineos
    container_name: mineos
    restart: always
    ports:
      - "25560-25570:25560-25570"
    volumes:
      - ${USERDIR}/docker/mineos/data:/var/games/minecraft
    environment:
      - TZ=${TZ}
      - USER_NAME=bethington
      - USER_PASSWORD=${PASS}
    networks:
      - proxy
    labels:
      traefik.enable: "true"
      traefik.backend: mineos
      traefik.port: 8080
      traefik.frontend.rule: Host:mineos.${DOMAINNAME}
      traefik.docker.network: proxy

########## DATABASE SERVICES ###########
# mysql – MySQL is a widely used, open-source relational database management system (RDBMS).
  ghost-mysql:
    image: mysql:5.7
    container_name: ghost-mysql
    restart: always
    networks:
      - default
    volumes:
      - ${USERDIR}/docker/ghost-mysql/data:/var/lib/mysql
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      MYSQL_ROOT_PASSWORD: ${PASS}
      MYSQL_DATABASE: ghost
      MYSQL_USER: bethington
      MYSQL_PASSWORD: ${PASS}

# mysql – MySQL is a widely used, open-source relational database management system (RDBMS).
  adanation-mysql:
    image: mysql:5.7
    container_name: adanation-mysql
    restart: always
    networks:
      - default
    volumes:
      - ${USERDIR}/docker/adanation-mysql/data:/var/lib/mysql
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      MYSQL_ROOT_PASSWORD: ${PASS}
      MYSQL_DATABASE: adanation
      MYSQL_USER: bethington
      MYSQL_PASSWORD: ${PASS}

# mysql – MySQL is a widely used, open-source relational database management system (RDBMS).
  cloud-mysql:
    image: mysql:5.7
    container_name: cloud-mysql
    restart: always
    networks:
      - default
    volumes:
      - ${USERDIR}/docker/cloud-mysql/data:/var/lib/mysql
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      MYSQL_ROOT_PASSWORD: ${PASS}
      MYSQL_DATABASE: cloud
      MYSQL_USER: bethington
      MYSQL_PASSWORD: ${PASS}

# mysql – MySQL is a widely used, open-source relational database management system (RDBMS).
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - ${USERDIR}/docker/mysql/data:/var/lib/mysql
      - ${USERDIR}/docker/shared:/shared
    environment:
      MYSQL_ROOT_PASSWORD: ${PASS}


######### BLOCKCHAIN SERVICES ##########


######### GUIDEWIRE DOCUMENTATION ##########
# gwbcd – Guidewire Billing Center Docs
  gwbcd:
    image: httpd:2.4
    container_name: gwbcd
    hostname: gwbcd
    restart: always
    networks:
      - proxy
    volumes:
      - ${USERDIR}/docker/gwbcd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ${USERDIR}/docker/gwbcd/data:/usr/local/apache2/htdocs/
      - ${USERDIR}/docker/shared:/shared
    labels:
      traefik.enable: "true"
      traefik.backend: gwbcd
      traefik.port: 80
      traefik.frontend.rule: Host:gwbcd.${DOMAINNAME}
      traefik.docker.network: proxy

# gwccd – Guidewire Claims Center Docs
  gwccd:
    image: httpd:2.4
    container_name: gwccd
    hostname: gwccd
    restart: always
    networks:
      - proxy
    volumes:
      - ${USERDIR}/docker/gwccd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ${USERDIR}/docker/gwccd/data:/usr/local/apache2/htdocs/
      - ${USERDIR}/docker/shared:/shared
    labels:
      traefik.enable: "true"
      traefik.backend: gwccd
      traefik.port: 80
      traefik.frontend.rule: Host:gwccd.${DOMAINNAME}
      traefik.docker.network: proxy

# gwpcd – Guidewire Policy Center Docs
  gwpcd:
    image: httpd:2.4
    container_name: gwpcd
    hostname: gwpcd
    restart: always
    networks:
      - proxy
    volumes:
      - ${USERDIR}/docker/gwpcd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ${USERDIR}/docker/gwpcd/data:/usr/local/apache2/htdocs/
      - ${USERDIR}/docker/shared:/shared
    labels:
      traefik.enable: true
      traefik.backend: gwpcd
      traefik.port: 80
      traefik.frontend.rule: Host:gwpcd.${DOMAINNAME}
      traefik.docker.network: proxy
  
######### DOCKER RELATED ##########

# Watchtower - Automatic Update of Containers/Apps
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    hostname: watchtower
    restart: unless-stopped
    command: --schedule "0 0 23 * * SUN" --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
networks:
  proxy:
    external:
      name: proxy
  default:
    driver: bridge
